
PRO URL: https://docs.cloud.oracle.com/iaas/Content/Database/Tasks/mig-rman-cross-plat-transp-tablespace.htm
PRO NON-CDB TO CDB
PRO
PRO Not available in public release yet...
PRO Need more testing...